server:
  port: 8080
#-------------SPRING-CONFIG-------------#
spring:
  cloud:
    gateway:
      routes:
        - id: service-car
          uri: lb://service-car
          predicates:
            - Path=/service-car/**
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/service-order/**
  application:
    name: api-gateway
#-------------EUREKA-CONFIG-------------#
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true